### ISSUE TITLE
Excited to see you working on a Notion plugin for Steampipe!

### ISSUE THREAD

**Issue by e-gineer** [ygpark80/steampipe-plugin-notion#1]
Hey @ygpark80 ... Quick note to say thanks for starting work on this plugin!

If you have any questions about plugin development or need any help please don't hesitate to [ask in our Slack community](https://steampipe.io/community/join).

BTW, once it's ready (docs, examples, coverage) we'd love to include this plugin on the [Steampipe Hub](https://hub.steampipe.io) as well.

Let us know how we can help!

**Comment by ygpark80** [comment]
@e-gineer, thanks for reaching out! I made this plugin as an educational purpose for use within our company so it may take time but I will let you know once it's ready! It would be really great if it can be included on the Steampipe Hub! If you have any specific requirements or good examples, please let me know! Steampipe docs were a little bit confusing here and there. :P

**Comment by ygpark80** [comment]
https://steampipe.io/docs/develop/plugin-release-checklist

**Comment by e-gineer** [comment]
Great to see you found the link above, it's a good guide to getting a plugin "Hub ready". It looks long, but most items are easy to tick off. We're also happy to collaborate with you on that and do reviews - just ping us anytime in Slack :-)
